const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  listProfiles: () => ipcRenderer.invoke('profiles:list'),
  createProfile: (name, color, initial) => ipcRenderer.invoke('profiles:create', name, color, initial),
  updateProfile: (id, updates) => ipcRenderer.invoke('profiles:update', id, updates),
  pickProfileAvatar: (id) => ipcRenderer.invoke('profiles:pickAvatar', id),
  clearProfileAvatar: (id) => ipcRenderer.invoke('profiles:clearAvatar', id),
  deleteProfile: (id) => ipcRenderer.invoke('profiles:delete', id),
  listDeletedProfiles: () => ipcRenderer.invoke('profiles:listDeleted'),
  restoreProfile: (id) => ipcRenderer.invoke('profiles:restore', id),
  purgeDeletedProfile: (id) => ipcRenderer.invoke('profiles:purgeDeleted', id),
  setActiveProfile: (id) => ipcRenderer.invoke('profiles:setActive', id),
  loadMovies: () => ipcRenderer.invoke('movies:load'),
  saveMovies: (movies) => ipcRenderer.invoke('movies:save', movies),
  loadTrash: () => ipcRenderer.invoke('trash:load'),
  saveTrash: (trash) => ipcRenderer.invoke('trash:save', trash),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  searchTmdb: (query) => ipcRenderer.invoke('tmdb:search', query),
  getTmdbDetails: (tmdbId, mediaType) => ipcRenderer.invoke('tmdb:details', tmdbId, mediaType),
  getTmdbProviders: (tmdbId, mediaType) => ipcRenderer.invoke('tmdb:providers', tmdbId, mediaType),
  openTrailer: (tmdbId, mediaType) => ipcRenderer.invoke('tmdb:openTrailer', tmdbId, mediaType),
  getRecommendations: (tmdbId, mediaType) => ipcRenderer.invoke('tmdb:recommendations', tmdbId, mediaType),
  getTrending: () => ipcRenderer.invoke('tmdb:trending'),
  getProviderLogos: () => ipcRenderer.invoke('tmdb:providerLogos'),
  discoverByProviders: (providerIds, mediaTypes) => ipcRenderer.invoke('tmdb:discoverByProviders', providerIds, mediaTypes),
  listSubscriptions: () => ipcRenderer.invoke('subscriptions:list'),
  upsertSubscription: (platform, updates) => ipcRenderer.invoke('subscriptions:upsert', platform, updates),
  cancelSubscription: (platform) => ipcRenderer.invoke('subscriptions:cancel', platform),
  listSubscriptionHistory: () => ipcRenderer.invoke('subscriptions:historyList'),
  deleteSubscriptionHistory: (id) => ipcRenderer.invoke('subscriptions:historyDelete', id),
  listShareLists: () => ipcRenderer.invoke('shareLists:list'),
  saveShareList: (payload) => ipcRenderer.invoke('shareLists:save', payload),
  deleteShareList: (id) => ipcRenderer.invoke('shareLists:delete', id),
  openShareListImage: (id) => ipcRenderer.invoke('shareLists:openImage', id),
  exportData: () => ipcRenderer.invoke('data:export'),
  importData: () => ipcRenderer.invoke('data:import'),
  applyImportedBackup: (payload) => ipcRenderer.invoke('data:applyImport', payload),
  pickCsvFile: () => ipcRenderer.invoke('data:pickCsv'),
  openDataFolder: () => ipcRenderer.invoke('app:openDataFolder'),
  openBackupsFolder: () => ipcRenderer.invoke('app:openBackupsFolder'),
  runBackupNow: () => ipcRenderer.invoke('app:runBackupNow'),
  getAppVersion: () => ipcRenderer.invoke('app:getVersion'),
  checkForUpdates: () => ipcRenderer.invoke('updater:check'),
  installUpdate: () => ipcRenderer.invoke('updater:install'),
  onUpdaterStatus: (callback) => {
    const handler = (_event, status) => callback(status);
    ipcRenderer.on('updater:status', handler);
    return () => ipcRenderer.removeListener('updater:status', handler);
  },
});
